Adding more tests
qiita-spots/qp-qiime2 pull request #25
Opened 2018-11-03 17:03 UTC by antgonza

2018-11-03 19:06 UTC, charles-cowart requested changes

2018-11-03 19:06 UTC, charles-cowart commented on qp_qiime2/__init__.py
> +                    # we are gonna continue so we don't add this element twice
gonna = going to

2018-11-03 19:06 UTC, charles-cowart commented on qp_qiime2/__init__.py
> +                    # to replace the "nerd" names for user friendly ones
"nerd" = technical?

2018-11-03 19:06 UTC, charles-cowart commented on qp_qiime2/__init__.py
> +                        if mid not in mid:
This should be changed - it's confusing even if it does actually work.

2018-11-03 19:06 UTC, charles-cowart commented on qp_qiime2/tests/test_qiime2.py
> +            'qp-hide-paramThe beta diversity metric to be computed.': 'metric',
Just to confirm, is this okay, with no spaces or ' etc?
_'qp-hide-paramThe beta diversity..._

2018-11-03 19:25 UTC, antgonza commented on qp_qiime2/__init__.py
> +                        if mid not in mid:
I actually wrote it like that to make it easier to follow; do you have a suggestion?

2018-11-03 19:25 UTC, antgonza commented on qp_qiime2/tests/test_qiime2.py
> +            'qp-hide-paramThe beta diversity metric to be computed.': 'metric',
yup

2018-11-03 19:27 UTC, antgonza commented on qp_qiime2/__init__.py
> +                        if mid not in mid:
... or perhaps more explanation?

2018-11-03 19:59 UTC, charles-cowart commented on qp_qiime2/__init__.py
> +                        if mid not in mid:
'if mid not in mid'? At face value, how can it not be in itself?

2018-11-03 20:00 UTC, charles-cowart commented on qp_qiime2/__init__.py
> +                        if mid not in mid:
Or how can it be in itself? It reads a little confusing.

2018-11-03 20:00 UTC, antgonza commented on qp_qiime2/__init__.py
> +                        if mid not in mid:
duh! didn't see it until now, fixing!

2018-11-04 01:33 UTC, charles-cowart requested changes

2018-11-04 01:33 UTC, charles-cowart commented on .travis.yml
> +  # we are going to use the same qiime2 environmen to install qtp-diversity
environmen = environment

2018-11-04 01:33 UTC, charles-cowart commented on .travis.yml
> +  # we are goint to use the same qiime2 environmen to install qtp-visualization
goint = going

2018-11-04 05:07 UTC, charles-cowart approved these changes

2018-11-04 17:01 UTC, charles-cowart approved these changes

2018-11-04 17:01 UTC, charles-cowart commented on qp_qiime2/qp_qiime2.py
> +    "Faith's Phylogenetic Diversity": "faith_pd",
Confirmed, it's legal to have a trailing comma when declaring a dict.

2018-11-04 17:02 UTC, charles-cowart approved these changes

2018-11-04 20:46 UTC, merged