adding beta-div
qiita-spots/qp-qiime2 pull request #4
Opened 2017-06-14 20:56 UTC by antgonza

2017-06-14 21:26 UTC, antgonza commented
This will fail until https://github.com/qiita-spots/qtp-diversity/pull/3/files is merged.

2017-06-21 14:18 UTC, josenavas requested changes
Few comments

2017-06-21 14:18 UTC, josenavas commented on qp_qiime2/__init__.py
> +    'i-tree': ['choice:["default"]', 'default']}
Since the default metric is not phylogenetic, should the default here be "No tree" or something along those lines?

2017-06-21 14:18 UTC, josenavas commented on qp_qiime2/__init__.py
> +         '"chebyshev", "canberra", "unweighted", "weighted-normalized", '
shouldn't it be 'unweighted unifrac', 'weighted-normalized unifrac' and 'weighted-unnormalized unifrac'?

2017-06-21 14:18 UTC, josenavas commented on qp_qiime2/qiime2.py
> +    if tree is not None and metric in STATE_UNIFRAC_METRICS:
If the metric is in STATE_UNIFRAC_METRICS, but the tree is None this if will evaluate to false and go by default to non-phylogenetic metric, which is incorrect. I think this `if-else` block is missing an `else if tree is None and metric in STATE_UNIFRAC_METRICS` that returns an error.

2017-06-21 14:18 UTC, josenavas commented on qp_qiime2/__init__.py
> +outputs = {'dissimilarity-table': 'distance_matrix'}
`dissimilarity-table`? I think `distance-matrix` is more user friendly - plus is the nomenclature used in Q2.

2017-06-21 14:18 UTC, josenavas commented on qp_qiime2/qiime2.py
> +    ainfo = [ArtifactInfo('%s distance matrix' % metric, 'distance_matrix',
`'%s distance matrix' % metric` -> `distance-matrix`. This needs to match the value in [here](https://github.com/qiita-spots/qp-qiime2/pull/4/files#diff-64e4811d769ef7e8391212a91ab4b5b0R50).

2017-06-21 14:18 UTC, josenavas commented on qp_qiime2/tests/test_qiime2.py
> +        # # actually test non phylogenetic beta diversity
Remove extra `#`

2017-06-21 14:18 UTC, josenavas commented on qp_qiime2/tests/test_qiime2.py
> +        self.assertEqual(True, success)
self.assertTrue(success)

2017-06-21 14:18 UTC, josenavas commented on qp_qiime2/tests/test_qiime2.py
> +        self.assertEqual('', msg)
Change the order of the parameters -> `self.assertEqual(msg, '')`. We typically use first observed, second expected.

2017-06-21 14:18 UTC, josenavas commented on qp_qiime2/tests/test_qiime2.py
> +        self.assertEqual(exp, ainfo[0].files)
same here regarding order.

2017-06-21 14:18 UTC, josenavas commented on qp_qiime2/tests/test_qiime2.py
> +        self.assertEqual('', msg)
Same comments as above.

2017-06-21 14:18 UTC, josenavas commented on qp_qiime2/tests/test_qiime2.py
> +        self.assertIn("Argument to input 'table' is not a subtype of "
Same comments as above regarding order.

2017-06-21 14:18 UTC, josenavas commented on qp_qiime2/tests/test_qiime2.py
> +        self.assertEqual(False, success)
`self.assertFalse(success)`

2017-06-21 15:31 UTC, josenavas requested changes

2017-06-21 15:31 UTC, josenavas commented on qp_qiime2/__init__.py
> +    beta_diversity, req_params, opt_params, outputs, dflt_param_set)
Sorry, just noticed this. Can you add "analysis_only=True" in here?

2017-06-21 18:12 UTC, josenavas commented on qp_qiime2/qiime2.py
> +                          [(ffp, 'distance_matrix')])]
Can you change this 'distance_matrix' by 'plain_text'? In this case, this represents the file type, which is technically just a plain text file.

2017-06-21 21:04 UTC, josenavas approved these changes

2017-06-21 21:22 UTC, josenavas approved these changes

2017-06-22 19:56 UTC, merged