qiime2-2019.10
qiita-spots/qp-qiime2 pull request #47
Opened 2019-11-04 21:56 UTC by antgonza

2019-11-05 17:34 UTC, ElDeveloper requested changes
Looks good, although adding some tests might be beneficial!

2019-11-05 17:34 UTC, ElDeveloper commented on qp_qiime2/qp_qiime2.py
>                         'is not a close reference table?')
This should be closed not close, right?

2019-11-05 17:34 UTC, ElDeveloper commented on qp_qiime2/__init__.py
> +def _get_qiime2_type_name_and_predicate(element):
Any way to have some tests for this function? I also am not sure I follow 100% what is going on. It seems like Union types have to be handled different but I don't understand what the first member is the representative member of the element.

2019-11-06 19:43 UTC, ElDeveloper requested changes
Thanks for adding tests. I've added a few minor changes but should be good to go otherwise.

2019-11-06 19:43 UTC, ElDeveloper commented on qp_qiime2/util.py
> +    name, predicate
```suggestion
    str, str
```

2019-11-06 19:43 UTC, ElDeveloper commented on qp_qiime2/util.py
> +        The name and the predite of the signature passed
```suggestion
        The name and the predicate of the inputed signature
```

2019-11-06 19:43 UTC, ElDeveloper commented on qp_qiime2/util.py
> +        # union types allow to give choises to another type of paramter; for
```suggestion
        # union types allow to give choices to another type of paramter; for
```

2019-11-06 19:43 UTC, ElDeveloper commented on qp_qiime2/util.py
> +        # example for a range(1, 10) give the choise `ignore`. These are not
```suggestion
        # example for a range(1, 10) give the choice `ignore`. These are not
```

2019-11-06 20:20 UTC, merged

2019-11-06 20:25 UTC, antgonza commented
Thank you soooo much!

2019-11-06 20:43 UTC, ElDeveloper commented
👍