ignore-tree-if-no-tree
qiita-spots/qp-qiime2 pull request #55
Opened 2020-11-05 14:15 UTC by antgonza

2020-11-05 19:48 UTC, antgonza commented
Solves https://github.com/biocore/qiita/issues/3039

2020-11-09 23:39 UTC, ElDeveloper requested changes

2020-11-09 23:39 UTC, ElDeveloper commented on qp_qiime2/qp_qiime2.py
> +        elif fpath is not None:
Can you add an `else` block and add a comment or error explaining what happens when this is the case? Does a None represent a Tree?

2020-11-10 22:13 UTC, ElDeveloper approved these changes

2020-11-10 22:13 UTC, ElDeveloper commented on qp_qiime2/qp_qiime2.py
> +            # future in might be useful to always ignore anything that doesn't
```suggestion
            # future it might be useful to always ignore anything that doesn't
```

2020-11-10 22:13 UTC, merged

2020-11-10 22:13 UTC, ElDeveloper commented
Thanks @antgonza